# Generated by Django 4.2.6 on 2023-11-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcing', '0002_task_completion_date_alter_project_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completion_date',
            new_name='end_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done')], max_length=10),
        ),
    ]
