# Generated by Django 4.2.6 on 2023-11-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcing', '0003_rename_completion_date_task_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
