# Generated by Django 4.2.6 on 2023-11-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcing', '0004_remove_task_end_date_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done')], max_length=10),
        ),
    ]
